[profile.release]
panic = 'unwind'

[workspace]
members = [
    'node',
    'runtime',
]

[patch."https://github.com/paritytech/substrate"]
beefy-gadget = { git = "https://github.com/octopus-network/substrate.git", branch = "polkadot-v0.9.12" }
beefy-gadget-rpc = { git = "https://github.com/octopus-network/substrate.git", branch = "polkadot-v0.9.12" }
beefy-primitives = { git = "https://github.com/octopus-network/substrate.git", branch = "polkadot-v0.9.12" }
frame-benchmarking-cli = { git = "https://github.com/octopus-network/substrate.git", branch = "polkadot-v0.9.12" }
frame-benchmarking = { git = "https://github.com/octopus-network/substrate.git", branch = "polkadot-v0.9.12" }
frame-executive = { git = "https://github.com/octopus-network/substrate.git", branch = "polkadot-v0.9.12" }
frame-support = { git = "https://github.com/octopus-network/substrate.git", branch = "polkadot-v0.9.12" }
frame-system-benchmarking = { git = "https://github.com/octopus-network/substrate.git", branch = "polkadot-v0.9.12" }
frame-system = { git = "https://github.com/octopus-network/substrate.git", branch = "polkadot-v0.9.12" }
frame-system-rpc-runtime-api = { git = "https://github.com/octopus-network/substrate.git", branch = "polkadot-v0.9.12" }
pallet-assets = { git = "https://github.com/octopus-network/substrate.git", branch = "polkadot-v0.9.12" }
pallet-authorship = { git = "https://github.com/octopus-network/substrate.git", branch = "polkadot-v0.9.12" }
pallet-babe = { git = "https://github.com/octopus-network/substrate.git", branch = "polkadot-v0.9.12" }
pallet-balances = { git = "https://github.com/octopus-network/substrate.git", branch = "polkadot-v0.9.12" }
pallet-beefy = { git = "https://github.com/octopus-network/substrate.git", branch = "polkadot-v0.9.12" }
pallet-beefy-mmr = { git = "https://github.com/octopus-network/substrate.git", branch = "polkadot-v0.9.12" }
pallet-grandpa = { git = "https://github.com/octopus-network/substrate.git", branch = "polkadot-v0.9.12" }
pallet-im-online = { git = "https://github.com/octopus-network/substrate.git", branch = "polkadot-v0.9.12" }
pallet-mmr = { git = "https://github.com/octopus-network/substrate.git", branch = "polkadot-v0.9.12" }
pallet-mmr-primitives = { git = "https://github.com/octopus-network/substrate.git", branch = "polkadot-v0.9.12" }
pallet-mmr-rpc = { git = "https://github.com/octopus-network/substrate.git", branch = "polkadot-v0.9.12" }
pallet-randomness-collective-flip = { git = "https://github.com/octopus-network/substrate.git", branch = "polkadot-v0.9.12" }
pallet-session = { git = "https://github.com/octopus-network/substrate.git", branch = "polkadot-v0.9.12" }
pallet-sudo = { git = "https://github.com/octopus-network/substrate.git", branch = "polkadot-v0.9.12" }
pallet-timestamp = { git = "https://github.com/octopus-network/substrate.git", branch = "polkadot-v0.9.12" }
pallet-transaction-payment = { git = "https://github.com/octopus-network/substrate.git", branch = "polkadot-v0.9.12" }
pallet-transaction-payment-rpc = { git = "https://github.com/octopus-network/substrate.git", branch = "polkadot-v0.9.12" }
pallet-transaction-payment-rpc-runtime-api = { git = "https://github.com/octopus-network/substrate.git", branch = "polkadot-v0.9.12" }
sc-basic-authorship = { git = "https://github.com/octopus-network/substrate.git", branch = "polkadot-v0.9.12" }
sc-chain-spec = { git = "https://github.com/octopus-network/substrate.git", branch = "polkadot-v0.9.12" }
sc-client-api = { git = "https://github.com/octopus-network/substrate.git", branch = "polkadot-v0.9.12" }
sc-cli = { git = "https://github.com/octopus-network/substrate.git", branch = "polkadot-v0.9.12", features = ['wasmtime'] }
sc-consensus-babe = { git = "https://github.com/octopus-network/substrate.git", branch = "polkadot-v0.9.12" }
sc-consensus-babe-rpc = { git = "https://github.com/octopus-network/substrate.git", branch = "polkadot-v0.9.12" }
sc-consensus-epochs = { git = "https://github.com/octopus-network/substrate.git", branch = "polkadot-v0.9.12" }
sc-consensus = { git = "https://github.com/octopus-network/substrate.git", branch = "polkadot-v0.9.12" }
sc-consensus-slots = { git = "https://github.com/octopus-network/substrate.git", branch = "polkadot-v0.9.12" }
sc-consensus-uncles = { git = "https://github.com/octopus-network/substrate.git", branch = "polkadot-v0.9.12" }
sc-executor = { git = "https://github.com/octopus-network/substrate.git", branch = "polkadot-v0.9.12", features = ['wasmtime'] }
sc-finality-grandpa = { git = "https://github.com/octopus-network/substrate.git", branch = "polkadot-v0.9.12" }
sc-finality-grandpa-rpc = { git = "https://github.com/octopus-network/substrate.git", branch = "polkadot-v0.9.12" }
sc-keystore = { git = "https://github.com/octopus-network/substrate.git", branch = "polkadot-v0.9.12" }
sc-network = { git = "https://github.com/octopus-network/substrate.git", branch = "polkadot-v0.9.12" }
sc-rpc-api = { git = "https://github.com/octopus-network/substrate.git", branch = "polkadot-v0.9.12" }
sc-rpc = { git = "https://github.com/octopus-network/substrate.git", branch = "polkadot-v0.9.12" }
sc-service = { git = "https://github.com/octopus-network/substrate.git", branch = "polkadot-v0.9.12", features = ['wasmtime'] }
sc-sync-state-rpc = { git = "https://github.com/octopus-network/substrate.git", branch = "polkadot-v0.9.12" }
sc-telemetry = { git = "https://github.com/octopus-network/substrate.git", branch = "polkadot-v0.9.12" }
sc-transaction-pool-api = { git = "https://github.com/octopus-network/substrate.git", branch = "polkadot-v0.9.12" }
sc-transaction-pool = { git = "https://github.com/octopus-network/substrate.git", branch = "polkadot-v0.9.12" }
sp-api = { git = "https://github.com/octopus-network/substrate.git", branch = "polkadot-v0.9.12" }
sp-authorship = { git = "https://github.com/octopus-network/substrate.git", branch = "polkadot-v0.9.12" }
sp-block-builder = { git = "https://github.com/octopus-network/substrate.git", branch = "polkadot-v0.9.12" }
sp-blockchain = { git = "https://github.com/octopus-network/substrate.git", branch = "polkadot-v0.9.12" }
sp-consensus-babe = { git = "https://github.com/octopus-network/substrate.git", branch = "polkadot-v0.9.12" }
sp-consensus = { git = "https://github.com/octopus-network/substrate.git", branch = "polkadot-v0.9.12" }
sp-core = { git = "https://github.com/octopus-network/substrate.git", branch = "polkadot-v0.9.12" }
sp-finality-grandpa = { git = "https://github.com/octopus-network/substrate.git", branch = "polkadot-v0.9.12" }
sp-inherents = { git = "https://github.com/octopus-network/substrate.git", branch = "polkadot-v0.9.12" }
sp-io = { git = "https://github.com/octopus-network/substrate.git", branch = "polkadot-v0.9.12" }
sp-keystore = { git = "https://github.com/octopus-network/substrate.git", branch = "polkadot-v0.9.12" }
sp-offchain = { git = "https://github.com/octopus-network/substrate.git", branch = "polkadot-v0.9.12" }
sp-runtime = { git = "https://github.com/octopus-network/substrate.git", branch = "polkadot-v0.9.12" }
sp-session = { git = "https://github.com/octopus-network/substrate.git", branch = "polkadot-v0.9.12" }
sp-staking = { git = "https://github.com/octopus-network/substrate.git", branch = "polkadot-v0.9.12" }
sp-std = { git = "https://github.com/octopus-network/substrate.git", branch = "polkadot-v0.9.12" }
sp-timestamp = { git = "https://github.com/octopus-network/substrate.git", branch = "polkadot-v0.9.12" }
sp-transaction-pool = { git = "https://github.com/octopus-network/substrate.git", branch = "polkadot-v0.9.12" }
sp-transaction-storage-proof = { git = "https://github.com/octopus-network/substrate.git", branch = "polkadot-v0.9.12" }
sp-version = { git = "https://github.com/octopus-network/substrate.git", branch = "polkadot-v0.9.12" }
substrate-build-script-utils = { git = "https://github.com/octopus-network/substrate.git", branch = "polkadot-v0.9.12" }
substrate-frame-rpc-system = { git = "https://github.com/octopus-network/substrate.git", branch = "polkadot-v0.9.12" }
substrate-wasm-builder = { git = "https://github.com/octopus-network/substrate.git", branch = "polkadot-v0.9.12" }
